#
#~/.zshrc
#

# my zshrc, it sucks but it works for me.

#a couple of good opts.
setopt autocd
setopt correct #adds support for command correction for typos

#Setup history 
setopt appendhistory
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

#Completion things
autoload -Uz +X compinit && compinit


# case insensitive path-completion
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*' menu select

#color support
autoload -U colors && colors


#Some of my aliases i use
alias sudo="doas"
alias ls="eza -a --icons --group-directories-first";
alias cls="clear && hyfetch --args='--config examples/12.jsonc'";
alias vpn_connected="curl https://am.i.mullvad.net/connected"
alias cd="z"
alias ll="ls -lh"
alias cat="bat --theme=Nord"
alias grep="rg"
alias clock="tty-clock -csBb"

#initializw zoxide
eval "$(zoxide init zsh)"

#Initialize starship
eval "$(starship init zsh)" 

#good path additions

#run on start to run neofetch
cls
