#
#~/.zshrc
#

# my zshrc, it sucks but it works for me.

#a couple of good opts.
setopt autocd
setopt correct #adds support for command correction for typos

#Setup history 
setopt appendhistory
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

#Completion things
autoload -Uz +X compinit && compinit


# case insensitive path-completion
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*' menu select

#color support
autoload -U colors && colors

#Some of my aliases i use
alias ls="eza -a --icons --group-directories-first";
alias cls="clear && hyfetch --args='--config examples/10.jsonc'";

alias cd="z"
alias ll="ls -lh"
alias cat="bat --theme=Nord"
alias grep="rg"
alias clock="tty-clock -csBb"


#initialize zoxide
eval "$(zoxide init zsh)"

#Set up the prompts.
#PROMPT="%F{52}[%f%F{094}%n%f%F{14}@%f%F{094}%m%f %F{017}%~%f%F{52}]%f%F{22}%(?.√.?%?)%%%f "
#RPROMPT="%@|%D{%a %b %d}"


#good path additions
export PATH="$PATH:/bin:/usr/bin:home/yujirodogma/.config/rofi/scripts:/home/yujirodogma/.cargo/bin:/home/yujirodogma/.local/bin:/home/yujirodogma/.spicetify:/home/yujirodogma/scripts/"

eval "$(starship init zsh)"
source ~/path/to/fsh/fast-syntax-highlighting.plugin.zsh
