#!/bin/bash

# Run the original xbps command
doas xbps-install "$@"

# Check if the xbps command was successful (exit code 0)
if [ $? -eq 0 ]; then
  # Execute your desired command here
  echo "xbps command finished. Updating module..."
  polybar-msg action "#updates.hook.0"
  echo "Done!"
  echo "Goodbye."
fi
