#!/bin/python


#
#~/.config/river/init
#

#My river init.
#barebones but it works for me.
#in python because why the hell not, shell is boring imo


import subprocess 
import time

def run_command(command):
    """Helper function to run shell commands."""
    try:
        subprocess.run(command, check=True, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    except subprocess.CalledProcessError as e:
        print(f"Error running command: {e.cmd}")
        print(f"STDOUT: {e.stdout.decode()}")
        print(f"STDERR: {e.stderr.decode()}")
    except FileNotFoundError:
        print(f"Command not found: {command.split()[0]}")

#run my keybindings file
with open("/home/yujirodogma/.config/river/keybindings.py", "r") as f:
    exec(f.read())

#run my autostarts file
with open("/home/yujirodogma/.config/river/autostarts.py", "r") as f:
    exec(f.read())



#misc setup options
run_command("riverctl set-repeat 50 300")
run_command("riverctl rule-add -app-id 'float*' -title 'foo' float")
run_command("riverctl rule-add ssd")
run_command("riverctl focus-follows-cursor always")
run_command("riverctl border-color-focused 0x83c092")
run_command("riverctl border-color-unfocused 0x3b4252")
run_command("riverctl border-width 2")
run_command("riverctl input pointer-1160-4180-CRQ1080:00_0488:1054_Touchpad tap enabled")

#set up layout
run_command("/home/yujirodogma/.config/river/set_up_layout.sh")
run_command("riverctl send-layout-cmd wideriver '--layout left --stack dwindle --count 1 --ratio 0.5'")
