#!/bin/python


#
#~/.config/river/init
#

#My river init.
#barebones but it works for me.
#in python because why the hell not, shell is boring imo


#keybinds are stored in keybindings.py and autostart programs are stored in autostarts.py

import subprocess 
import time
import os
def run_command(command):
    """Helper function to run shell commands."""
    try:
        subprocess.run(command, check=True, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    except subprocess.CalledProcessError as e:
        print(f"Error running command: {e.cmd}")
        print(f"STDOUT: {e.stdout.decode()}")
        print(f"STDERR: {e.stderr.decode()}")
    except FileNotFoundError:
        print(f"Command not found: {command.split()[0]}")

#run my keybindings file
subprocess.run(['python', '/home/yujirodogma/.config/river/keybindings.py'])
#run my autostarts file
subprocess.run(['python', '/home/yujirodogma/.config/river/autostarts.py'])



#misc setup options
run_command("riverctl set-repeat 50 300")
run_command("riverctl rule-add -app-id 'float*' -title 'foo' float")
run_command("riverctl rule-add ssd")
run_command("riverctl focus-follows-cursor always")
run_command("riverctl border-color-focused 0x83c092")
run_command("riverctl border-color-unfocused 0x3b4252")
run_command("riverctl border-width 2")
run_command("riverctl input pointer-1160-4180-CRQ1080:00_0488:1054_Touchpad tap enabled")
run_command("riverctl xcursor-theme 'everforest-cursors' 24")
run_command("export QT_QPA_PLATFORMTHEME=qt6ct")
run_command("export QT_QPA_PLATFORM=wayland")

#set up layout
command_for_layout = """
riverctl default-layout wideriver
wideriver \
    --layout                       left        \
    --layout-alt                   monocle     \
    --stack                        dwindle     \
    --count-master                 1           \
    --ratio-master                 0.50        \
    --count-wide-left              0           \
    --ratio-wide                   0.35        \
    --no-smart-gaps                            \
    --inner-gaps                   4           \
    --outer-gaps                   4           \
    --border-width                 2           \
    --border-width-monocle         0           \
    --border-width-smart-gaps      0           \
    --border-color-focused         "0x83c092"  \
    --border-color-focused-monocle "0x83c092"  \
    --border-color-unfocused       "0x3b4252"  \
    --log-threshold                info        \
   > "/tmp/wideriver.${XDG_VTNR}.${USER}.log" 2>&1 &
"""
run_command(command_for_layout)
run_command("riverctl send-layout-cmd wideriver '--layout left --stack dwindle --count 1 --ratio 0.5'")
